
import 'dart:developer' as developer;
import 'dart:math';

import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:ticketapp/main.dart';

import '../../model/otp_result.dart';

class UserRepository{

  /*
      Supabase
      Co siÄ™ stanie?
      ğŸ”¹  Nie istnieje w bazie	Supabase tworzy nowe konto
      ğŸ”¹  JuÅ¼ istnieje	Supabase normalnie loguje uÅ¼ytkownika
   */


  Future<Result> sendOtp(String phoneNumber) async{
    try{
      await supabase.auth.signInWithOtp(phone: phoneNumber.toString());
      return Result.success();
    }on AuthException catch(e){
      developer.log('AuthException (OTP): ${e.message}');
      return Result.failure(e.message);
    }catch(e){
      developer.log('BÅ‚Ä…d wysyÅ‚ania OTP: $e');
      return  Result.failure('errorUnknown');
    }
  }

  Future<Result> verifyOtp(String phoneNumber, String token) async {
    try {
      final response = await supabase.auth.verifyOTP(
        phone: phoneNumber,
        token: token,
        type: OtpType.sms,
      );

      if (response.session != null && response.user != null) {
        return Result.success();
      } else {
        return Result.failure('Nie udaÅ‚o siÄ™ zalogowaÄ‡. SprÃ³buj ponownie.');
      }
    } on AuthException catch (e) {
      developer.log('BÅ‚Ä…d weryfikacji OTP: ${e.message}');
      return Result.failure(e.message);
    } catch (e) {
      developer.log('Inny bÅ‚Ä…d: $e');
      return Result.failure('WystÄ…piÅ‚ nieoczekiwany bÅ‚Ä…d.');
    }
  }

  Future<Result> logOut() async{
    try{
      await supabase.auth.signOut();
      //await _storage.write(key: 'authToken', value: '');
      return Result.success();

    }on AuthException catch(e){
      developer.log('AuthException: ${e.message}');
      return Result.failure(e.message);
    } catch(e){
      developer.log('BÅ‚Ä…d przy wylogowywaniu: $e');
      return Result.failure('WystÄ…piÅ‚ nieoczekiwany bÅ‚Ä…d.SprÃ³buj ponownie.');
    }
  }

  Future<Result> deleteAccount() async{
    try{
      final response = await supabase.functions.invoke('delete_user_account', body: {'name': 'Functions'});
      if(response.status == 200){
        return Result.success();
      }else{
        final errorMessage = response.data['error'] ?? 'Nieznany bÅ‚Ä…d';
        return Result.failure(errorMessage);
      }

    }catch(e){
      return Result.failure('WystÄ…piÅ‚ nieoczekiwany bÅ‚Ä…d.SprÃ³buj ponownie.');
    }
  }

}